### ISSUE TITLE
[hakari] The about's documentation has a sentence that ends abruptly, missing information.

### ISSUE THREAD

**Issue by duchainer** [guppy-rs/guppy#254]
I saw the issue so I wanted to report it, but feel free to close if it is not relevant enough. :sweat_smile: 

I suppose that some diagram or more in-depth explanation was expected to follow :

https://github.com/guppy-rs/guppy/blob/deb475343f4ccc5ec4295ab97c99eaefd37fc28b/tools/cargo-hakari/src/docs/about.rs#L106-L109

I don't use this crate yet, so I don't really know what should be going here specifically, but hopefully someone else with the knowledge will.

**Comment by sunshowers** [comment]
Fixed in https://github.com/guppy-rs/guppy/commit/c34e155677b49696179387b056f5b4e2c068d626. Thanks!
